version: '3'
services:
  moresandevaluation: 
    build: .
    image: "rifak/my-nginx:latest"
    container_name: "helloworldrifak"
    ports:
      - "80:80"
    depends_on:
      - db
  db:
    build: .
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
    volumes:
      - ./mydb.sql:/docker-entrypoint-initdb.d/mydb.sql
    command: mysqld
